package com.muratdayan.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF4B0076)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF7623AD)
val onPrimaryContainerLight = Color(0xFFFBECFF)
val secondaryLight = Color(0xFF785A00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFCA4B)
val onSecondaryContainerLight = Color(0xFF503A00)
val tertiaryLight = Color(0xFF006C49)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF65F1B3)
val onTertiaryContainerLight = Color(0xFF004C32)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF7FD)
val onBackgroundLight = Color(0xFF1F1A22)
val surfaceLight = Color(0xFFFFF7FD)
val onSurfaceLight = Color(0xFF1F1A22)
val surfaceVariantLight = Color(0xFFEDDEF0)
val onSurfaceVariantLight = Color(0xFF4D4352)
val outlineLight = Color(0xFF7F7383)
val outlineVariantLight = Color(0xFFD0C2D4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342E37)
val inverseOnSurfaceLight = Color(0xFFF9EDF9)
val inversePrimaryLight = Color(0xFFE3B5FF)
val surfaceDimLight = Color(0xFFE2D7E2)
val surfaceBrightLight = Color(0xFFFFF7FD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFCF0FC)
val surfaceContainerLight = Color(0xFFF6EAF6)
val surfaceContainerHighLight = Color(0xFFF0E5F1)
val surfaceContainerHighestLight = Color(0xFFEADFEB)


val primaryDark = Color(0xFFE3B5FF)
val onPrimaryDark = Color(0xFF4D007A)
val primaryContainerDark = Color(0xFF5A008D)
val onPrimaryContainerDark = Color(0xFFE6BBFF)
val secondaryDark = Color(0xFFFFEED0)
val onSecondaryDark = Color(0xFF3F2E00)
val secondaryContainerDark = Color(0xFFF9BC00)
val onSecondaryContainerDark = Color(0xFF463300)
val tertiaryDark = Color(0xFFDFFFEB)
val onTertiaryDark = Color(0xFF003824)
val tertiaryContainerDark = Color(0xFF57E5A8)
val onTertiaryContainerDark = Color(0xFF00442C)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF171119)
val onBackgroundDark = Color(0xFFEADFEB)
val surfaceDark = Color(0xFF171119)
val onSurfaceDark = Color(0xFFEADFEB)
val surfaceVariantDark = Color(0xFF4D4352)
val onSurfaceVariantDark = Color(0xFFD0C2D4)
val outlineDark = Color(0xFF998D9D)
val outlineVariantDark = Color(0xFF4D4352)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEADFEB)
val inverseOnSurfaceDark = Color(0xFF342E37)
val inversePrimaryDark = Color(0xFF8536BC)
val surfaceDimDark = Color(0xFF171119)
val surfaceBrightDark = Color(0xFF3D3740)
val surfaceContainerLowestDark = Color(0xFF110C14)
val surfaceContainerLowDark = Color(0xFF1F1A22)
val surfaceContainerDark = Color(0xFF231E26)
val surfaceContainerHighDark = Color(0xFF2E2831)
val surfaceContainerHighestDark = Color(0xFF39333C)

val customBlueLight = Color(0xFF006A6A)
val onCustomBlueLight = Color(0xFFFFFFFF)
val customBlueContainerLight = Color(0xFF23EFEF)
val onCustomBlueContainerLight = Color(0xFF004A4A)

val customBlueDark = Color(0xFFCDFFFE)
val onCustomBlueDark = Color(0xFF003737)
val customBlueContainerDark = Color(0xFF00E2E2)
val onCustomBlueContainerDark = Color(0xFF004141)